### ISSUE TITLE
`velState` message doesn't follow ROS naming conventions.

### ISSUE THREAD

**Issue by Joroba3** [ARUSfs/DRIVERLESS#20]
The [`velState.msg`](https://github.com/ARUSfs/DRIVERLESS/blob/30f6adcb3c25bbf01acef337ce16e98c8a21dd40/src/common/common_msgs/msg/velState.msg) doesn't change naming conventions. Should be changed to `VelState` in definition and all references in python.

**Comment by jormunrod** [comment]
Fixed. I have deleted it because the implementation does not require it.

**Comment by Joroba3** [comment]
[The message is still there](https://github.com/ARUSfs/DRIVERLESS/blob/79b907de35cb31873b4609d9af0c3e35beb64a24/src/common/common_msgs/msg/vel_state.msg), just with a different name (that doesn't follow naming conventions either).

**Comment by jormunrod** [comment]
Mental bug, solved!
